#!/usr/bin/env bash
# Above line specifies the interpreter to be used for executing the script (bash)

# This script configures a new Ubuntu machine by installing Nginx and 
# setting it up to serve a page with "Hello World".

# Print a message indicating that Nginx installation is starting
echo -e "Updating and installing Nginx.\n"

# Update package lists and install Nginx silently (-y) to avoid prompts
sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y

# Print a message indicating that some minor setup tasks are being performed
echo -e "\nSetting up some minor stuff.\n"

# Start Nginx service
sudo service nginx start

# Allow Nginx  through the firewall
sudo ufw allow "Nginx HTTP"

# Give the user ownership of website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index file with "Hello world!" content using dd command
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restart Nginx to apply changes
sudo service nginx restart

# print a message indicating that the setup is completed
echo -e "\nCompleted. ✅\n"
