#!/usr/bin/env bash
# script to duplicate web-01 to web-02
# This script automates the setup of a web server using Nginx on a Debian-based system

# uncomment the following line to enable debug
# set-x

echo -e "Updating and doing minor checks...\n"

# Function to check if a command is available, and if not, install it
function install(){
  # Check if the command is not available
  if ! command -v "$1" &> /dev/null; then
	  echo -e "  Installing: $1$\n"
	  # Update package repositories and install the specified package
          sudo apt-get update -y -qq  && \
		  sudo apt-get install -y "$1" -qq
          echo -e "\n"
  else
          # Command is already installed
          echo -e "  ${1} is already installed.\n"
  fi
}
# Install Nginx
install nginx

echo -e "\nSetting up some stuff.\n"

# Allowing Nginx on the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
if [ -d "/var/www" ]; then
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
else
	sudo mkdir -p /var/www
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
fi

# Create directories if not present
for dir in /var/www/{html,error}; do
	if ! [ -d "$dir" ]; then
		mkdir -p "$dir"
	fi
done

# Creating new index
echo "Hello World!" > /var/www/html/index.html

# Create a new error page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# Backup default server config file
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

# Define the new server configuraration
server_config="server {
                 listen 80 default_server;
	         listen [::]:80 default_server;
	         root /var/www/html;
	         index index.html index.htm index.nginx-debian.html;
	         server_name _;
	         add_header X-Served-By \$hostname;
	         location / {
		     try_files \$uri \$uri/ =404;
	         }
	         if (\$request_filename ~ redirect_me){
			 rewrite ^ https://th3-gr00t.tk/ permanent;
		 }
	         error_page 404 /error_404.html;
	         location = /error_404.html {
	             internal;
       }
}"

# Check if Nginx is running and start /restart accordingly
if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi

