#!/usr/bin/env bash
#Displays lines containing the ""bash" word to get the PID of the Bash process.
#shellcheck disable=SC2009

#use ps command to list all proceses with aditional information
#filter line containing the word "bash" using grep
ps -aux | grep bash
