#!/usr/bin/env bash
#This script displays the username, user id, and home directory path for each user in /etc/passwd

#Reading /etc/passwd line by line
while IFS=':' read -r username _ uid _ homedir _; do
	echo "$username:$uid:$homedir"
done < /etc/passwd
