#!/usr/bin/env bash
#This script groups visitors by IP and HTTP status code, and displays the data
#Using awk to extract IP and HTTP status code from the Apache log file,
#then counting occurrences of each combination and sorting the result
awk '{print $1, $9}' apache-access.log |sort | uniq -c | sort -nr
