#!/usr/bin/env bash
#checks if the file exists
if [ -e "school" ]; then
	echo "school file exists"
	#checks if the file is empty
	if [ -s "school" ]; then
		echo "school file does not exist"
	else
		echo "school file is empty"
	fi
	#checks if the file is regular file
	if [ -f "school" ]; then
		echo "school is a regular file"
	fi

else
	echo "school file does not exist"
fi
