#!/usr/bin/env bash
#configured an ubuntu server as follows:
# - local host resolves to 127.0.0.2
# -FACEBOOK.COM RESOLVES TO 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com " >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts

